<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pembelian</name>
   <tag></tag>
   <elementGuidId>ad9acc4c-2e57-403f-9156-feb1cd58d2ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[text()=&quot;Pembelian&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[text()=&quot;Pembelian&quot;]</value>
   </webElementProperties>
</WebElementEntity>
